name: Flutter Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
        
      - name: Build APK
        run: flutter build apk --release
        
      - name: Build App Bundle
        run: flutter build appbundle --release
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-${{ github.sha }}
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
          
      - name: Upload App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: appbundle-${{ github.sha }}
          path: build/app/outputs/bundle/release/app-release.aab
          retention-days: 7 